[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gree = "85VjuYCNKnfYo9kk1YTuWVhq975xtgJg3Ur5tU5ZAzxJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/asimnecip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
