[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gree = "CLt2j2maYmipHnZziRUdyZ9a7jBy7TV1jLrRBMdEw8eL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asimnecip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
