[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gree = "GoVMQGBCHedXGAyVC2aAo7G9Bm4tusTWSRmtDVRWpsgQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/asimnecip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
